pipelines:
  default:
    - step:
        name: Build and run tests for PHP 5.6
        image: php:5.6-cli
        script:
            - apt-get update && apt-get install -y libevent-dev libssl-dev
            - docker-php-ext-install sockets
            - sockets_ini=$(php -i | grep -m 1 -o -E '/.*sockets\.ini') && test -z "$sockets_ini" || mv -v "$sockets_ini" "$(echo "$sockets_ini" | sed -e 's/sockets.ini/0-sockets.ini/')"
            - docker-php-source extract
            - phpize
            - ./configure --with-event-core --with-event-extra --with-event-openssl
            - make install
            - echo 'extension=event.so' > /usr/local/etc/php/conf.d/z-event.ini
            - NO_INTERACTION=1 TEST_PHP_EXECUTABLE=$(which php) php run-tests.php
            - docker-php-source delete
    - step:
        name: Build and run tests for PHP 7.3
        image: php:7.3-cli
        script:
            - apt-get update && apt-get install -y libevent-dev libssl-dev
            - docker-php-ext-install sockets
            - sockets_ini=$(php -i | grep -m 1 -o -E '/.*sockets\.ini') && test -z "$sockets_ini" || mv -v "$sockets_ini" "$(echo "$sockets_ini" | sed -e 's/sockets.ini/0-sockets.ini/')"
            - docker-php-source extract
            - phpize
            - ./configure --with-event-core --with-event-extra --with-event-openssl
            - make install
            - echo 'extension=event.so' > /usr/local/etc/php/conf.d/z-event.ini
            - NO_INTERACTION=1 TEST_PHP_EXECUTABLE=$(which php) php run-tests.php
            - docker-php-source delete
    - step:
        name: Build and run tests for PHP 7.4
        image: php:7.4-cli
        script:
            - apt-get update && apt-get install -y libevent-dev libssl-dev
            - docker-php-ext-install sockets
            - sockets_ini=$(php -i | grep -m 1 -o -E '/.*sockets\.ini') && test -z "$sockets_ini" || mv -v "$sockets_ini" "$(echo "$sockets_ini" | sed -e 's/sockets.ini/0-sockets.ini/')"
            - docker-php-source extract
            - phpize
            - ./configure --with-event-core --with-event-extra --with-event-openssl
            - make install
            - echo 'extension=event.so' > /usr/local/etc/php/conf.d/z-event.ini
            - NO_INTERACTION=1 TEST_PHP_EXECUTABLE=$(which php) php run-tests.php
            - docker-php-source delete
