pipelines:
  default:
    - step:
        name: Build and run tests for PHP 7.4
        image: php:7.4-cli
        script:
            - apt-get update && apt-get install -y libevent-dev libssl-dev
            - docker-php-ext-install sockets && docker-php-ext-enable --ini-name 0-sockets.ini sockets
            - docker-php-source extract
            - phpize
            - ./configure --with-event-core --with-event-extra --with-event-openssl --with-openssl-dir
            - make install
            - docker-php-ext-enable --ini-name z-event.ini event
            - NO_INTERACTION=1 TEST_PHP_EXECUTABLE=$(which php) php run-tests.php
            - docker-php-source delete
    - step:
        name: Build and run tests for PHP 8.1
        image: php:8.1-cli
        script:
            - apt-get update && apt-get install -y libevent-dev libssl-dev
            - docker-php-ext-install sockets && docker-php-ext-enable --ini-name 0-sockets.ini sockets
            - docker-php-source extract
            - phpize
            - ./configure --with-event-core --with-event-extra --with-event-openssl --with-openssl-dir
            - make install
            - docker-php-ext-enable --ini-name z-event.ini event
            - NO_INTERACTION=1 TEST_PHP_EXECUTABLE=$(which php) php run-tests.php
            - docker-php-source delete
    - step:
        name: Build and run tests for PHP 8.2
        image: php:8.2-cli
        script:
            - apt-get update && apt-get install -y libevent-dev libssl-dev
            - docker-php-ext-install sockets && docker-php-ext-enable --ini-name 0-sockets.ini sockets
            - docker-php-source extract
            - phpize
            - ./configure --with-event-core --with-event-extra --with-event-openssl --with-openssl-dir
            - make install
            - docker-php-ext-enable --ini-name z-event.ini event
            - NO_INTERACTION=1 TEST_PHP_EXECUTABLE=$(which php) php run-tests.php
            - docker-php-source delete
    - step:
        name: Build and run tests for PHP 8
        image: php:8-cli
        script:
            - apt-get update && apt-get install -y libevent-dev libssl-dev
            - docker-php-ext-install sockets && docker-php-ext-enable --ini-name 0-sockets.ini sockets
            - docker-php-source extract
            - phpize
            - ./configure --with-event-core --with-event-extra --with-event-openssl --with-openssl-dir
            - make install
            - docker-php-ext-enable --ini-name z-event.ini event
            - NO_INTERACTION=1 TEST_PHP_EXECUTABLE=$(which php) php run-tests.php
            - docker-php-source delete
