version: '3'

services:
    php8test:
        stdin_open: true
        image: ruslanosmanov/pecl-event-php8-test
        build:
            context: .
            dockerfile: php8/Dockerfile
    php81test:
        stdin_open: true
        image: ruslanosmanov/pecl-event-php81-test
        build:
            context: .
            dockerfile: php8/Dockerfile-php8.1
    php82test:
        stdin_open: true
        image: ruslanosmanov/pecl-event-php82-test
        build:
            context: .
            dockerfile: php8/Dockerfile-php8.2
    php84test:
        stdin_open: true
        image: ruslanosmanov/pecl-event-php84-test
        build:
            context: .
            dockerfile: php8/Dockerfile-php8.4
    php7test:
        stdin_open: true
        image: ruslanosmanov/pecl-event-php7-test
        build:
            context: .
            dockerfile: php7/Dockerfile

    php7rhel8test:
        stdin_open: true
        image: ruslanosmanov/pecl-event-php7rhel8-test
        build:
            context: .
            dockerfile: php7/Dockerfile.rhel8
